# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile - JexOS build system
#
# Targets:
#   all             Build kernel + disk image (default)
#   run             Launch in QEMU (GUI)
#   clean           Remove build artifacts
#   distclean       Remove everything (incl. build directory)
#   docs            Generate Doxygen HTML documentation
#   iso             Build bootable GRUB ISO
#   help            Show this help
#
# Options:
#   V=1             Verbose output (show full commands)
#   DEBUG=1         Build with ftrace instrumentation

## Toolchain 
CC        = gcc
AS        = as
LD        = ld
HOSTCC    = gcc
QEMU      = qemu-system-i386

## Architecture 
CFLAGS    = -m32 -ffreestanding -std=gnu99 -fno-pie
CFLAGS   += -O2 -Wall -Wextra
CFLAGS   += -fno-omit-frame-pointer
CFLAGS   += -Isrc/include -Isrc/tests
ASFLAGS   = --32
LDFLAGS   = -m elf_i386 -T linker.ld -nostdlib

# ftrace support (see src/debug/ftrace.c)
ifeq ($(DEBUG),1)
CFLAGS += -finstrument-functions
endif

## Output files
KERNEL    = jexos.bin
IMG       = jexos.img
ISO       = jexos.iso
BUILD     = build
OBJ_DIR   = $(BUILD)/obj

## Source discovery
SRC_C     = $(shell find src -name '*.c' ! -path '*/lib/type.c')
SRC_S     = $(shell find src/arch -name '*.s')
OBJECTS   = $(patsubst src/%.c, $(OBJ_DIR)/%.o, $(SRC_C)) \
            $(patsubst src/%.s, $(OBJ_DIR)/%.o, $(SRC_S))

## Dependency files (auto-generated by -MMD) 
DEPS      = $(OBJECTS:.o=.d)

## Host tools 
MKJEXFS   = $(BUILD)/tools/mkjexfs
GEN_KS    = $(BUILD)/tools/gen_kallsyms
KALLSYMS_S = src/kernel/kallsyms_data.S

## Rootfs (trigger disk image rebuild when these change) 
ROOTFS_FILES = $(wildcard rootfs/*)


Q         = @
ifneq ($(V),1)
Q         = @
endif
 
all: $(KERNEL) $(IMG)

$(KERNEL): $(OBJECTS) $(GEN_KS)
	$(Q)printf "  LD      $@\n"
	$(Q)$(LD) $(LDFLAGS) -o $@.tmp $(OBJECTS)
	$(Q)nm -n -S $@.tmp | $(GEN_KS) > $(KALLSYMS_S)
	$(Q)$(AS) $(ASFLAGS) $(KALLSYMS_S) -o $(OBJ_DIR)/kallsyms_data.o
	$(Q)$(LD) $(LDFLAGS) -o $@ $(OBJECTS) $(OBJ_DIR)/kallsyms_data.o
	$(Q)rm -f $@.tmp
	$(Q)printf "  KERNEL  $@ (`wc -c < $@` bytes)\n"

$(IMG): $(MKJEXFS) $(ROOTFS_FILES)
	$(Q)printf "  IMG     $@\n"
	$(Q)./$(MKJEXFS) $@ 4096

$(OBJ_DIR)/%.o: src/%.c
	$(Q)mkdir -p $(@D)
	$(Q)printf "  CC      $<\n"
	$(Q)$(CC) $(CFLAGS) -MMD -MP -c $< -o $@

$(OBJ_DIR)/%.o: src/%.s
	$(Q)mkdir -p $(@D)
	$(Q)printf "  AS      $<\n"
	$(Q)$(AS) $(ASFLAGS) $< -o $@


$(GEN_KS): tools/gen_kallsyms.c
	$(Q)mkdir -p $(@D)
	$(Q)printf "  HOSTCC $<\n"
	$(Q)$(HOSTCC) -o $@ $<

$(MKJEXFS): tools/mkjexfs.c
	$(Q)mkdir -p $(@D)
	$(Q)printf "  HOSTCC $<\n"
	$(Q)$(HOSTCC) -o $@ $<


$(ISO): $(KERNEL) $(IMG)
	$(Q)printf "  ISO     $@\n"
	$(Q)mkdir -p iso/boot/grub
	$(Q)cp $(KERNEL) iso/boot/
	$(Q)cp $(IMG) iso/boot/
	@if [ ! -f iso/boot/grub/grub.cfg ]; then \
		echo 'set timeout=5' > iso/boot/grub/grub.cfg; \
		echo 'menuentry "JexOS" {' >> iso/boot/grub/grub.cfg; \
		echo '    multiboot /boot/jexos.bin' >> iso/boot/grub/grub.cfg; \
		echo '    boot' >> iso/boot/grub/grub.cfg; \
		echo '}' >> iso/boot/grub/grub.cfg; \
	fi
	$(Q)grub2-mkrescue -o $@ iso

iso: $(ISO)


docs:
	$(Q)printf "  DOXYGEN\n"
	$(Q)doxygen Doxyfile

docs-run: docs
	$(Q)printf "  SERVE   http://localhost:8000\n"
	$(Q)cd docs/html && python3 -m http.server 8000

run: $(KERNEL) $(IMG)
	$(Q)printf "  QEMU    %s\n" "$(QEMU)"
	$(Q)$(QEMU) -kernel $(KERNEL) -hda $(IMG) -serial stdio \
	       -machine pcspk-audiodev=audio0 -audiodev pa,id=audio0 \
	       -netdev user,id=net0,hostfwd=tcp::8080-:80 \
	       -device rtl8139,netdev=net0


clean:
	$(Q)printf "  CLEAN\n"
	rm -rf $(BUILD) $(KERNEL) $(IMG) $(ISO) $(KALLSYMS_S) iso/

distclean: clean
	$(Q)printf "  DISTCLEAN\n"
	rm -rf iso/


help:
	@echo "JexOS Build System"
	@echo ""
	@echo "Targets:"
	@echo "  make              Build kernel + disk image"
	@echo "  make run          Launch in QEMU (GUI)"
	@echo "  make docs         Generate HTML docs via Doxygen"
	@echo "  make docs-run     Generate docs + serve at :8000"
	@echo "  make iso          Build GRUB bootable ISO"
	@echo "  make clean        Remove build artifacts"
	@echo "  make distclean    Remove everything"
	@echo ""
	@echo "Options:"
	@echo "  V=1               Verbose output"
	@echo "  DEBUG=1           Build with ftrace"
	@echo ""

-include $(DEPS)

.PHONY: all run clean distclean iso docs docs-run help
