/*
 * ftrace.c - Lightweight function tracer
 *
 * Purpose: Implements a 4096-entry ring buffer that records function
 *          entry/exit events generated by gcc -finstrument-functions.
 *          Events are resolved to symbolic names via kallsyms. A simple
 *          substring filter limits output to functions of interest.
 * Design:  The fast path (__cyg_profile_func_enter/exit) is O(1) -- it
 *          stores (func, call_site, type) into the ring buffer with no
 *          memory allocation or name resolution. Name resolution and
 *          filtering happen only on ftrace_dump().
 * Thread-safety: Intended for UP. The head index is volatile but not
 *                protected by a lock. Interrupts should be disabled
 *                around the tracer fast path or the buffer must be sized
 *                to absorb worst-case interrupt nesting.
 */
#define pr_fmt(fmt) "[FTRACE] " fmt
#include "debug/ftrace.h"
#include "kernel/printk.h"
#include "kernel/kallsyms.h"

static ftrace_record_t ftrace_buf[FTRACE_BUF_SIZE];
static volatile unsigned int ftrace_head = 0;
static volatile int ftrace_enabled = 0;

#define FTRACE_MAX_FILTERS 16
static char ftrace_filters[FTRACE_MAX_FILTERS][32];
static int filter_count = 0;
static int filter_all = 1;

void ftrace_enable(void)
{
    ftrace_enabled = 1;
    pr_info("ftrace enabled\n");
}

void ftrace_disable(void)
{
    ftrace_enabled = 0;
    pr_info("ftrace disabled\n");
}

int ftrace_is_enabled(void)
{
    return ftrace_enabled;
}

void ftrace_add_filter(const char* substr)
{
    if (filter_count >= FTRACE_MAX_FILTERS)
        return;
    int i = 0;
    while (*substr && i < 31)
        ftrace_filters[filter_count][i++] = *substr++;
    ftrace_filters[filter_count][i] = '\0';
    filter_count++;
    filter_all = 0;
    pr_info("added filter: %s\n", ftrace_filters[filter_count - 1]);
}

void ftrace_clear_filters(void)
{
    filter_count = 0;
    filter_all = 1;
    pr_info("filters cleared\n");
}

/*
 * matches_filter - Check if function name contains any active filter
 * @name: Function name from kallsyms
 *
 * Returns 1 if the name matches (or no filters are set).
 */
static int matches_filter(const char* name)
{
    if (filter_all)
        return 1;

    for (int f = 0; f < filter_count; f++) {
        const char* fn = name;
        while (*fn) {
            const char* fsub = ftrace_filters[f];
            const char* fpos = fn;
            while (*fsub && *fpos && *fsub == *fpos) {
                fsub++;
                fpos++;
            }
            if (*fsub == '\0')
                return 1;
            fn++;
        }
    }
    return 0;
}

/* Suppress -Winfinite-recursion false positive: GCC does not instrument
 * __cyg_profile_func_* itself, but the analyzer can't determine this.
 * The attribute also provides a belt-and-suspenders guard.
 */
__attribute__((no_instrument_function))
void __cyg_profile_func_enter(void* func, void* call_site)
{
    (void)call_site;
    if (!ftrace_enabled)
        return;

    unsigned int idx = ftrace_head;
    ftrace_buf[idx].func   = (uint32_t)func;
    ftrace_buf[idx].caller = (uint32_t)call_site;
    ftrace_buf[idx].type   = FTRACE_ENTRY;
    ftrace_head = (idx + 1) % FTRACE_BUF_SIZE;
}

__attribute__((no_instrument_function))
void __cyg_profile_func_exit(void* func, void* call_site)
{
    (void)call_site;
    if (!ftrace_enabled)
        return;

    unsigned int idx = ftrace_head;
    ftrace_buf[idx].func   = (uint32_t)func;
    ftrace_buf[idx].caller = (uint32_t)call_site;
    ftrace_buf[idx].type   = FTRACE_EXIT;
    ftrace_head = (idx + 1) % FTRACE_BUF_SIZE;
}

void ftrace_dump(void)
{
    if (!ftrace_enabled) {
        pr_info("ftrace is disabled -- no data recorded\n");
        return;
    }

    pr_info("ftrace dump (%u records in buffer):\n", ftrace_head);
    for (unsigned int i = 0; i < FTRACE_BUF_SIZE; i++) {
        unsigned int idx = (ftrace_head + i) % FTRACE_BUF_SIZE;
        if (ftrace_buf[idx].type == 0)
            continue;

        uint32_t off, sz;
        const char* fn = kallsyms_lookup(ftrace_buf[idx].func, &off, &sz);
        if (!fn) continue;

        if (!matches_filter(fn)) continue;

        const uint32_t caller_off = ftrace_buf[idx].caller;
        const char* arrow = (ftrace_buf[idx].type == FTRACE_ENTRY) ? "->" : "<-";

        uint32_t c_off, c_sz;
        const char* caller_fn = kallsyms_lookup(caller_off, &c_off, &c_sz);
        if (caller_fn)
            pr_info("  %s %s+0x%x (from %s+0x%x)\n",
                   arrow, fn, off, caller_fn, c_off);
        else
            pr_info("  %s %s+0x%x (from 0x%x)\n",
                   arrow, fn, off, caller_off);
    }
}
