/**
 * @file gen_kallsyms.c
 * @brief Generate packed kallsyms symbol table assembly from nm output.
 *
 * Reads nm -n -S output from stdin, extracts text symbols (T/t), sorts them,
 * and emits a .S file with the packed symbol table in the .kallsyms section.
 *
 * Usage: nm -n -S kernel.elf | gen_kallsyms > kallsyms_data.S
 *
 * The output layout:
 *   __kallsyms_start:
 *     .long count                     // number of entries
 *     // For each symbol (sorted by address):
 *     .long addr                      // function address
 *     .long (name_off & 0xFFFFFF) | (packed_size << 24)  // name offset + size/16
 *     // Then all null-terminated names concatenated:
 *     __kallsyms_strings:
 *     .asciz "func1"
 *     .asciz "func2"
 *     ...
 */

#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

typedef struct {
    uint32_t addr;
    uint32_t size;
    char*    name;
} symbol_t;

int sym_cmp(const void* a, const void* b)
{
    return ((symbol_t*)a)->addr - ((symbol_t*)b)->addr;
}

int main(void)
{
    symbol_t syms[4096];
    int count = 0;
    char line[512];

    while (fgets(line, sizeof(line), stdin) && count < 4096) {
        uint32_t addr, size;
        char type[4], name[256];
        if (sscanf(line, "%x %x %3s %255s", &addr, &size, type, name) >= 4) {
            if (type[0] == 'T' || type[0] == 't') {
                syms[count].addr = addr;
                syms[count].size = size;
                syms[count].name = strdup(name);
                count++;
            }
        }
    }

    qsort(syms, count, sizeof(symbol_t), sym_cmp);

    printf("# Auto-generated by gen_kallsyms\n");
    printf(".section .kallsyms, \"a\"\n");
    printf(".globl __kallsyms_start\n");
    printf(".globl __kallsyms_end\n");
    printf("__kallsyms_start:\n");

    printf(".long %d\n", count);

    int string_offset = 0;
    for (int i = 0; i < count; i++) {
        uint32_t pack_size = (syms[i].size + 15) / 16;
        if (pack_size > 255) pack_size = 255;

        uint32_t hi = (string_offset & 0xFFFFFF) | (pack_size << 24);
        printf(".long 0x%08x\n", syms[i].addr);
        printf(".long 0x%08x\n", hi);

        string_offset += strlen(syms[i].name) + 1;
    }

    printf("__kallsyms_strings:\n");
    for (int i = 0; i < count; i++) {
        printf(".asciz \"%s\"\n", syms[i].name);
    }

    printf("__kallsyms_end:\n");
    return 0;
}
